---
- name: Clean yum metadata
  ansible.builtin.command: yum clean metadata
  args:
    warn: no
  become: true

- name: Reload systemd configuration
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart scylla
  become: true
  ansible.builtin.service:
    name: scylla-server
    state: restarted
    enabled: yes

- name: Stop scylla
  become: true
  ansible.builtin.service:
    name: scylla-server
    state: stopped

- name: Start node_exporter
  become: true
  ansible.builtin.service:
    name: node-exporter
    state: started
    enabled: yes

- name: Enable and start 'scylla-fstrim.timer' service
  ansible.builtin.service:
    name: scylla-fstrim.timer
    state: started
    enabled: yes
  become: true

- name: Start scylla-manager-agent
  become: true
  ansible.builtin.service:
    name: scylla-manager-agent
    state: started
    enabled: true

- name: Stop scylla-manager-agent
  become: true
  ansible.builtin.service:
    name: scylla-manager-agent
    state: stopped

- name: Restart scylla-manager-agent
  become: true
  ansible.builtin.service:
    name: scylla-manager-agent
    state: restarted
