---
- name: Validate that all nodes are up before adjusting the replication
  ansible.builtin.uri:
    url: "http://{{ scylla_api_address }}:{{ scylla_api_port }}/failure_detector/endpoints/"
    follow_redirects: none
    method: GET
  register: _result
  until: _result.status == 200
  retries: 10
  delay: 1

- name: Get datacenter name
  ansible.builtin.uri:
    url: "http://{{ scylla_api_address }}:{{ scylla_api_port }}/snitch/datacenter"
    method: GET
  register: _datacenter_out
  until: _datacenter_out.status == 200
  retries: 5
  delay: 1

- name: Prepare per DC replication_factor list
  ansible.builtin.set_fact:
    dcs_to_rf: '{{ dcs_to_rf | default([]) + ["''" + hostvars[item][''_datacenter_out''].json + "'':" + _keyspace_rf | string] }}'
  loop: "{{ groups['scylla'] }}"
  run_once: true

- ansible.builtin.set_fact:
    scylla_admin_username: "{{ scylla_admin_default_user }}"
    scylla_admin_password: "{{ lookup('ini', scylla_admin_default_user, section='cql_credentials', allow_no_value=true, default=omit, file=inventory_file) }}"
  when: scylla_admin_default_user is defined and 'cql_credentials' in groups

- ansible.builtin.fail:
    msg: "Make sure that {{ scylla_admin_default_user }} is defined in the 'cql_credentials' section"
  when: scylla_admin_default_user is defined and scylla_admin_password is not defined

- ansible.builtin.set_fact:
    scylla_admin_username: "cassandra"
    scylla_admin_password: "cassandra"
  when: scylla_admin_default_user is not defined

- name: Adjust replication for {{ _keyspace }} keyspace
  ansible.builtin.shell: |
    cqlsh {{ broadcast_address }} -u {{ scylla_admin_username }} -p {{ scylla_admin_password }} -e "ALTER KEYSPACE {{ _keyspace }} WITH replication = {'class': '{{ _keyspace_replication_strategy }}', {{ dcs_to_rf | unique | join(',') }}};"
  run_once: true

- name: Run cleanup
  async_task:
    ansible.builtin.shell: |
      nodetool cleanup {{ _keyspace }}
    alias: scylla_cleanup
    async: "{{ cleanup_timeout_seconds }}"
    retries: "{{ cleanup_timeout_seconds // 30 }}" # retries = cleanup_timeout_seconds / delay
    delay: 30
  register: _cleanup_output

- name: Cleanup logs
  ansible.builtin.debug: var=_cleanup_output

- name: Run repair
  ansible.builtin.include_tasks: repair.yml
  vars:
    keyspace: "{{ _keyspace }}"
