---
- name: Check for pre-existing agent-token file
  ansible.builtin.stat:
    path: "{{ cluster_local_files_path }}/scyllamgr_auth_token.txt"
  register: token_file_stat
  run_once: true
  delegate_to: localhost

- name: Generate a new token file
  when: token_file_stat.stat.islnk is not defined
  block:
    - name: Generate the agent key
      ansible.builtin.shell: |
        LC_CTYPE=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 128 | head -n 1
      register: scyllamgr_auth_token
      delegate_to: localhost
      run_once: true

    - name: Store the auth token in a local file for later use
      ansible.builtin.copy:
        content: |
          {{ scyllamgr_auth_token.stdout }}
        dest: "{{ cluster_local_files_path }}/scyllamgr_auth_token.txt"
      delegate_to: localhost
      run_once: true

- name: Read the key from auth token file
  ansible.builtin.slurp:
    src: "{{ cluster_local_files_path }}/scyllamgr_auth_token.txt"
  register: b64auth_token
  delegate_to: localhost
  run_once: true

- name: Decode data and store as fact
  ansible.builtin.set_fact:
    auth_token: "{{ b64auth_token.content | b64decode }}"
  delegate_to: localhost
  run_once: true

- name: Apply the configuration data to scylla-manager-agent.yaml
  ansible.builtin.template:
    src: templates/scylla-manager-agent.yaml.j2
    dest: /etc/scylla-manager-agent/scylla-manager-agent.yaml
    owner: root
    group: root
    mode: "0644"
  become: true
  register: manager_agent_config_change

- name: Run scyllamgr_agent_setup
  ansible.builtin.shell: |
    scyllamgr_agent_setup -y
  become: true
  when: manager_agent_config_change.changed

- name: Start and enable the Manager agent service
  ansible.builtin.service:
    name: scylla-manager-agent
    state: restarted
    enabled: yes
  become: true
  when: manager_agent_config_change.changed and start_scylla_service is defined and start_scylla_service|bool
  ignore_errors: true
  #TODO: remove ignore_errors when ansible is bumped to 2.10.4 or 2.9.16 as per https://github.com/ansible/ansible/issues/71528
